name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fastapi-app/requirements.txt
      - name: Run tests with coverage
        run: |
          PYTHONPATH=fastapi-app python -m pytest \
            --cov=fastapi-app \
            --cov-report=term-missing \
            --cov-fail-under=80
